-- Bulk Insert Products
-- Generated from server/products_data.ts

-- Ensure categories exist (or use fallback ID 1)
-- Map Slugs: test-bank -> 1 (Nursing), others may default to 1 for simplicity in this bulk seed
-- Ideally we would map them dynamically but for SQL we need to be explicit.
-- Based on analysis: most products are 'test-bank', some are 'test-bank-fundamentals-of-nursing'
-- We will insert them linked to Category ID 1 (Nursing) as a default safe fallback for "Test Banks".

INSERT INTO products (title, slug, short_description, long_description, price, image_url, category_id, author, edition, is_best_seller, review_count) VALUES
('Wong''s Essentials of Pediatric Nursing 10th Edition Test Bank', 'wong-s-essentials-of-pediatric-nursing-10th-edition-test-bank', 'Wong''s Essentials of Pediatric Nursing 10th Edition Test Bank', 'Wong''s Essentials of Pediatric Nursing 10th Edition Test Bank\n\nWhat is a test bank?\nA test bank comprises a curated collection of exam questions...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Wongs-Essentials-of-Pediatric-Nursing-10th-Edition-Test-Bank.webp', 1, 'Unknown', '10th Edition', FALSE, 20),
('Williams'' Basic Nutrition and Diet Therapy 15th Edition Test Bank', 'williams-basic-nutrition-and-diet-therapy-15th-edition-test-bank', 'Williams'' Basic Nutrition and Diet Therapy 15th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Williams-Basic-Nutrition-and-Diet-Therapy-15th-Edition-Test-Bank.webp', 1, 'Unknown', '15th Edition', FALSE, 20),
('Wilkins'' Clinical Assessment in Respiratory Care 8th Edition Test Bank', 'wilkins-clinical-assessment-in-respiratory-care-8th-edition-test-bank', 'Wilkins'' Clinical Assessment in Respiratory Care 8th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Wilkins-Clinical-Assessment-in-Respiratory-Care-8th-Edition-Test-Bank.webp', 1, 'Unknown', '8th Edition', FALSE, 4),
('Understanding Nursing Research 8th Edition Test Bank', 'understanding-nursing-research-8th-edition-test-bank', 'Understanding Nursing Research 8th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Understanding-Nursing-Research-8th-Edition-Test-Bank.webp', 1, 'Unknown', '8th Edition', FALSE, 14),
('Touhy Ebersole & Hess'' Gerontological Nursing and Healthy Aging 2nd Canadian Edition Test Bank', 'touhy-ebersole-hess-gerontological-nursing-and-healthy-aging-2nd-canadian-edition-test-bank', 'Touhy Ebersole & Hess'' Gerontological Nursing and Healthy Aging 2nd Canadian Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Touhy-Ebersole-Hess-Gerontological-Nursing-and-Healthy-Aging-2nd-Canadian-Edition-Test-Bank.webp', 1, 'Unknown', '1st Edition', FALSE, 11),
('The Muscular System Manual 4th Edition Test Bank', 'the-muscular-system-manual-4th-edition-test-bank', 'The Muscular System Manual 4th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/The-Muscular-System-Manual-4th-Edition-Test-Bank.webp', 1, 'Unknown', '4th Edition', FALSE, 7),
('The Language of Medicine 11th Edition by Davi-Ellen Chabner Test Bank', 'the-language-of-medicine-11th-edition-by-davi-ellen-chabner-test-bank', 'The Language of Medicine 11th Edition by Davi-Ellen Chabner Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/The-Language-of-Medicine-11th-Edition-by-Davi-Ellen-Chabner-Test-Bank.webp', 1, 'Davi', '11th Edition', FALSE, 2),
('The Human Body in Health and Illness 6th Edition Test Bank', 'the-human-body-in-health-and-illness-6th-edition-test-bank', 'The Human Body in Health and Illness 6th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/The-Human-Body-in-Health-and-Illness-6th-Edition-Test-Bank.webp', 1, 'Unknown', '6th Edition', FALSE, 12),
('The Human Body in Health & Disease 7th Edition Test Bank', 'the-human-body-in-health-disease-7th-edition-test-bank', 'The Human Body in Health & Disease 7th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/The-Human-Body-in-Health-Disease-7th-Edition-Test-Bank.webp', 1, 'Unknown', '7th Edition', FALSE, 2),
('Textbook of Diagnostic Sonography 8th Edition Test Bank', 'textbook-of-diagnostic-sonography-8th-edition-test-bank', 'Textbook of Diagnostic Sonography 8th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Textbook-of-Diagnostic-Sonography-8th-Edition-Test-Bank.webp', 1, 'Unknown', '8th Edition', FALSE, 6),
('Textbook of Diagnostic Microbiology 6th Edition Test Bank', 'textbook-of-diagnostic-microbiology-6th-edition-test-bank', 'Textbook of Diagnostic Microbiology 6th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Textbook-of-Diagnostic-Microbiology-6th-Edition-Test-Bank.webp', 1, 'Unknown', '6th Edition', FALSE, 10),
('Sonography 5th Edition by Reva Arnez Curry Test Bank', 'sonography-5th-edition-by-reva-arnez-curry-test-bank', 'Sonography 5th Edition by Reva Arnez Curry Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Sonography-5th-Edition-by-Reva-Arnez-Curry-Test-Bank.webp', 1, 'Reva Arnez Curry Test Bank', '5th Edition', FALSE, 2),
('Radiologic Science for Technologists 11th Edition Test Bank', 'radiologic-science-for-technologists-11th-edition-test-bank', 'Radiologic Science for Technologists 11th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Radiologic-Science-for-Technologists-11th-Edition-Test-Bank.webp', 1, 'Unknown', '11th Edition', FALSE, 5),
('Radiographic Pathology for Technologists 7th Edition by Nina Kowalczyk Test Bank', 'radiographic-pathology-for-technologists-7th-edition-by-nina-kowalczyk-test-bank', 'Radiographic Pathology for Technologists 7th Edition by Nina Kowalczyk Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Radiographic-Pathology-for-Technologists-7th-Edition-by-Nina-Kowalczyk-Test-Bank.webp', 1, 'Nina Kowalczyk Test Bank', '7th Edition', FALSE, 14),
('Quick & Easy Medical Terminology 8th Edition by Peggy C. Leonard Test Bank', 'quick-easy-medical-terminology-8th-edition-by-peggy-c-leonard-test-bank', 'Quick & Easy Medical Terminology 8th Edition by Peggy C. Leonard Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Quick-Easy-Medical-Terminology-8th-Edition-by-Peggy-C.-Leonard-Test-Bank.webp', 1, 'Peggy C. Leonard Test Bank', '8th Edition', FALSE, 4),
('Radiation Protection in Medical Radiography 8th Edition Test Bank', 'radiation-protection-in-medical-radiography-8th-edition-test-bank', 'Radiation Protection in Medical Radiography 8th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Radiation-Protection-in-Medical-Radiography-8th-Edition-Test-Bank.webp', 1, 'Unknown', '8th Edition', FALSE, 16),
('Public Health Nursing 10th Edition by Marcia Stanhope Test Bank', 'public-health-nursing-10th-edition-by-marcia-stanhope-test-bank', 'Public Health Nursing 10th Edition by Marcia Stanhope Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Public-Health-Nursing-10th-Edition-by-Marcia-Stanhope-Test-Bank.webp', 1, 'Marcia Stanhope Test Bank', '10th Edition', FALSE, 7),
('Psychiatric Nursing 8th Edition by Norman L. Keltner Test Bank', 'psychiatric-nursing-8th-edition-by-norman-l-keltner-test-bank', 'Psychiatric Nursing 8th Edition by Norman L. Keltner Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Psychiatric-Nursing-8th-Edition-by-Norman-L.-Keltner-Test-Bank.webp', 1, 'Norman L. Keltner Test Bank', '8th Edition', FALSE, 14),
('Professional Nursing 10th Edition by Beth Black Test Bank', 'professional-nursing-10th-edition-by-beth-black-test-bank', 'Professional Nursing 10th Edition by Beth Black Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Professional-Nursing-10th-Edition-by-Beth-Black-Test-Bank.webp', 1, 'Beth Black Test Bank', '10th Edition', FALSE, 6),
('Primary Care 6th Edition by Terry Mahan Buttaro Test Bank', 'primary-care-6th-edition-by-terry-mahan-buttaro-test-bank', 'Primary Care 6th Edition by Terry Mahan Buttaro Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Primary-Care-6th-Edition-by-Terry-Mahan-Buttaro-Test-Bank.webp', 1, 'Terry Mahan Buttaro Test Bank', '6th Edition', FALSE, 5),
('Practice Management for the Dental Team 9th Edition Test Bank', 'practice-management-for-the-dental-team-9th-edition-test-bank', 'Practice Management for the Dental Team 9th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Practice-Management-for-the-Dental-Team-9th-Edition-Test-Bank.webp', 1, 'Unknown', '9th Edition', FALSE, 6),
('Potter Canadian Fundamentals of Nursing 6th Edition Test Bank', 'potter-canadian-fundamentals-of-nursing-6th-edition-test-bank', 'Potter Canadian Fundamentals of Nursing 6th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Potter-Canadian-Fundamentals-of-Nursing-6th-Edition-Test-Bank.webp', 1, 'Unknown', '6th Edition', FALSE, 4),
('Patient Care in Radiography 10th Edition by Ruth Ann Ehrlich Test Bank', 'patient-care-in-radiography-10th-edition-by-ruth-ann-ehrlich-test-bank', 'Patient Care in Radiography 10th Edition by Ruth Ann Ehrlich Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Patient-Care-in-Radiography-10th-Edition-by-Ruth-Ann-Ehrlich-Test-Bank.webp', 1, 'Ruth Ann Ehrlich Test Bank', '10th Edition', FALSE, 6),
('Pagana Mosby''s Canadian Manual of Diagnostic and Laboratory Tests 2nd Canadian Edition Test Bank', 'pagana-mosby-s-canadian-manual-of-diagnostic-and-laboratory-tests-2nd-canadian-edition-test-bank', 'Pagana Mosby''s Canadian Manual of Diagnostic and Laboratory Tests 2nd Canadian Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Pagana-Mosbys-Canadian-Manual-of-Diagnostic-and-Laboratory-Tests-2nd-Canadian-Edition-Test-Bank.webp', 1, 'Unknown', '1st Edition', FALSE, 3),
('Oral Pathology for the Dental Hygienist 7th Edition by Olga A. C. Ibsen Test Bank', 'oral-pathology-for-the-dental-hygienist-7th-edition-by-olga-a-c-ibsen-test-bank', 'Oral Pathology for the Dental Hygienist 7th Edition by Olga A. C. Ibsen Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Oral-Pathology-for-the-Dental-Hygienist-7th-Edition-by-Olga-A.-C.-Ibsen-Test-Bank.webp', 1, 'Olga A. C. Ibsen Test Bank', '7th Edition', FALSE, 4),
('Nursing Today 10th Edition by JoAnn Zerwekh Test Bank', 'nursing-today-10th-edition-by-joann-zerwekh-test-bank', 'Nursing Today 10th Edition by JoAnn Zerwekh Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Nursing-Today-10th-Edition-by-JoAnn-Zerwekh-Test-Bank.webp', 1, 'JoAnn Zerwekh Test Bank', '10th Edition', FALSE, 1),
('Nursing Delegation and Management of Patient Care 3rd Edition Test Bank', 'nursing-delegation-and-management-of-patient-care-3rd-edition-test-bank', 'Nursing Delegation and Management of Patient Care 3rd Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Nursing-Delegation-and-Management-of-Patient-Care-3rd-Edition-Test-Bank.webp', 1, 'Unknown', '3rd Edition', FALSE, 5),
('Nuclear Medicine and PETCT 8th Edition Test Bank', 'nuclear-medicine-and-petct-8th-edition-test-bank', 'Nuclear Medicine and PETCT 8th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Nuclear-Medicine-and-PETCT-8th-Edition-Test-Bank.webp', 1, 'Unknown', '8th Edition', FALSE, 19),
('Neonatal and Pediatric Respiratory Care 5th Edition Test Bank', 'neonatal-and-pediatric-respiratory-care-5th-edition-test-bank', 'Neonatal and Pediatric Respiratory Care 5th Edition Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Neonatal-and-Pediatric-Respiratory-Care-5th-Edition-Test-Bank.webp', 1, 'Unknown', '5th Edition', FALSE, 9),
('Mulholland''s The Nurse The Math The Meds 4th Edition by Susan Turner Test Bank', 'mulholland-s-the-nurse-the-math-the-meds-4th-edition-by-susan-turner-test-bank', 'Mulholland''s The Nurse The Math The Meds 4th Edition by Susan Turner Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Mulhollands-The-Nurse-The-Math-The-Meds-4th-Edition-by-Susan-Turner-Test-Bank.webp', 1, 'Susan Turner Test Bank', '4th Edition', FALSE, 14),
('Mosby''s Pathology for Massage Therapists 4th Edition by Susan G. Salvo Test Bank', 'mosby-s-pathology-for-massage-therapists-4th-edition-by-susan-g-salvo-test-bank', 'Mosby''s Pathology for Massage Therapists 4th Edition by Susan G. Salvo Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Mosbys-Pathology-for-Massage-Therapists-4th-Edition-by-Susan-G.-Salvo-Test-Bank.webp', 1, 'Susan G. Salvo Test Bank', '4th Edition', FALSE, 7),
('Mosby''s Canadian Textbook for the Support Worker 4th Edition Test Bank', 'mosby-s-canadian-textbook-for-the-support-worker-4th-edition-test-bank', 'Mosby''s Canadian Textbook for the Support Worker 4th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Mosbys-Canadian-Textbook-for-the-Support-Worker-4th-Edition-Test-Bank.webp', 1, 'Unknown', '4th Edition', FALSE, 17),
('Mosby’s Pharmacy Technician Exam Review 4th Edition by James Mizner Test Bank', 'mosby-s-pharmacy-technician-exam-review-4th-edition-by-james-mizner-test-bank', 'Mosby’s Pharmacy Technician Exam Review 4th Edition by James Mizner Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Mosbys-Pharmacy-Technician-Exam-Review-4th-Edition-by-James-Mizner-Test-Bank.webp', 1, 'James Mizner Test Bank', '4th Edition', FALSE, 12),
('Modern Dental Assisting 12th Edition by Doni L. Bird Test Bank', 'modern-dental-assisting-12th-edition-by-doni-l-bird-test-bank', 'Modern Dental Assisting 12th Edition by Doni L. Bird Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Modern-Dental-Assisting-12th-Edition-by-Doni-L.-Bird-Test-Bank.webp', 1, 'Doni L. Bird Test Bank', '12th Edition', FALSE, 2),
('Miller Infection Control and Management of Hazardous Materials for the Dental Team 6th Edition Test Bank', 'miller-infection-control-and-management-of-hazardous-materials-for-the-dental-team-6th-edition-test-bank', 'Miller Infection Control and Management of Hazardous Materials for the Dental Team 6th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Miller-Infection-Control-6th-Edition-Test-Bank.webp', 1, 'Unknown', '6th Edition', FALSE, 9),
('Merrill''s Atlas of Radiographic Positioning and Procedures 14th Edition Test Bank', 'merrill-s-atlas-of-radiographic-positioning-and-procedures-14th-edition-test-bank', 'Merrill''s Atlas of Radiographic Positioning and Procedures 14th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Merrills-Atlas-of-Radiographic-Positioning-and-Procedures-14th-Edition-by-Bruce-W.-Long-Test-Bank.webp', 1, 'Unknown', '14th Edition', FALSE, 10),
('Medical-Surgical Nursing 10th Edition by Donna D. Ignatavicius Test Bank', 'medical-surgical-nursing-10th-edition-by-donna-d-ignatavicius-test-bank', 'Medical-Surgical Nursing 10th Edition by Donna D. Ignatavicius Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Medical-Surgical-Nursing-10th-Edition-by-Donna-D.-Ignatavicius-Test-Bank.webp', 1, 'Donna D. Ignatavicius Test Bank', '10th Edition', FALSE, 8),
('Medical Terminology A Short Course 9th Edition by Davi-Ellen Chabner Test Bank', 'medical-terminology-a-short-course-9th-edition-by-davi-ellen-chabner-test-bank', 'Medical Terminology A Short Course 9th Edition by Davi-Ellen Chabner Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Medical-Terminology-A-Short-Course-9th-Editionby-Davi-Ellen-Chabner-Test-Bank.webp', 1, 'Davi', '9th Edition', FALSE, 18),
('Medical Terminology & Anatomy for Coding 3rd Edition by Betsy J. Shiland Test Bank', 'medical-terminology-anatomy-for-coding-3rd-edition-by-betsy-j-shiland-test-bank', 'Medical Terminology & Anatomy for Coding 3rd Edition by Betsy J. Shiland Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Medical-Terminology-Anatomy-for-Coding-3rd-Edition-by-Betsy-J.-Shiland-Test-Bank.webp', 1, 'Betsy J. Shiland Test Bank', '3rd Edition', FALSE, 6),
('McCurnin''s Clinical Textbook for Veterinary Technicians 9th Edition Test Bank', 'mccurnin-s-clinical-textbook-for-veterinary-technicians-9th-edition-test-bank', 'McCurnin''s Clinical Textbook for Veterinary Technicians 9th Edition Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/McCurnins-Clinical-Textbook-for-Veterinary-Technicians-9th-Edition-by-Joanna-M.-Bassert-Test-Bank.webp', 1, 'Unknown', '9th Edition', FALSE, 4),
('Mastering Healthcare Terminology 6th Edition by Betsy J. Shiland Test Bank', 'mastering-healthcare-terminology-6th-edition-by-betsy-j-shiland-test-bank', 'Mastering Healthcare Terminology 6th Edition by Betsy J. Shiland Test Bank', 'Full description pending...', 25.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/Mastering-Healthcare-Terminology-6th-Edition-by-Betsy-J.-Shiland-Test-Bank.webp', 1, 'Betsy J. Shiland Test Bank', '6th Edition', FALSE, 9),
('LPN to RN Transitions 4th Edition by Lora Claywell Test Bank', 'lpn-to-rn-transitions-4th-edition-by-lora-claywell-test-bank', 'LPN to RN Transitions 4th Edition by Lora Claywell Test Bank', 'Full description pending...', 45.00, 'https://studiazone-com-103170.hostingersite.com/wp-content/uploads/2023/10/LPN-to-RN-Transitions-4th-Edition-by-Lora-Claywell-Test-Bank.webp', 1, 'Lora Claywell Test Bank', '4th Edition', FALSE, 16);
